version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - $PWD/data:/data/db
    networks:
      - net

  reaction:
    image: reactioncommerce/reaction
    networks:
      - net
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      ROOT_URL: "http://192.168.1.65"
      MONGO_URL: "mongodb://mongo:27017/reaction"

networks:
  net:
